spring.application.name=practicespring

spring.datasource.url=jdbc:mysql://localhost:3306/java_devops?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=pa55word

spring.jpa.hibernate.ddl-auto=update